- config/release-integration.yml
This PR adds a config file for the Release Integration team.
Thanks,
Dave
> Add config for release-integration team

- config/release-integration.yml
> Update release-integration user IDs

- config/cli.yml
Have not had a chance to run `validate` script yet.
@acrmp could you maybe pull this down on your Mac and run it?
> Add CLI team to interrupt bot

- config/credhub.yml
> add credhub team

- config/garden-windows.yml
Update garden-windows slack bot to include new employee, Cara
Signed-off-by: Cara Sciorilli <csciorilli@pivotal.io>
> Add Cara to CF Slack bot

- config/cli.yml
[#166590430](https://www.pivotaltracker.com/story/show/166590430)
Co-authored-by: Alexander Berezovsky <aberezovsky@pivotal.io>
> Offboard Will from CLI team

- config/cli.yml
Co-authored-by: Alexander Berezovsky <aberezovsky@pivotal.io>
> On-board Steve onto CLI team

- config/release-integration.yml
Please reach out to the Release Integration team if you have any questions.
Thanks,
Andrew and @davewalter
> Replace Chris with Andrew Costa in RelInt team

- config/diego.yml
Co-authored-by: Maria Shaldibina <mshaldibina@pivotal.io>
> Add config file for Diego team

- config/release-integration.yml
Co-authored-by: Andrew Costa <acosta@pivotal.io>
> add weyman to relint team

- config/buildpacks.yml
Co-authored-by: David Freilich <dfreilich@pivotal.io>
> Create buildpacks interrupt config

- config/volume-services.yml
Co-authored-by: Dennis Leon <dleon@pivotal.io>
Co-authored-by: Lisa Cho <lcho@pivotal.io>
> Add volume services team config

- config/volume-services.yml
Co-authored-by: Dennis Leon <dleon@pivotal.io>
Co-authored-by: Lisa Cho <lcho@pivotal.io>
> Oops correct ids for volume services team

- config/release-integration.yml
and remove wfung for offboarding
Co-authored-by: Jaskanwal Pawar <jpawar@pivotal.io>
> Add jwal and jspin to release integration

- config/buildpacks.yml
* Remove Chhavi from it as well
[#170503528]
> Remove Zander from OSS interrupt bot

- config/cli.yml
Authored-by: Eric Promislow <eric.promislow@suse.com>
> Drop Joseph, add Eric to the CLI @interrupt list

- config/cli.yml
CLI team will also respond to interrupts from the VAT channel
> Add VAT Slack channel

- config/buildpacks.yml
> add kenny to slackbot

- config/cli.yml
- Offboard Brendan, Onboard Chris
- Alpha order the Pairist names
> Goodby Brendan, welcome Chris!

- config/volume-services.yml
> Update volume-services team

- config/platform-recovery.yml
Hi all,
Can we add the BBR team to the bot config please? Thanks!
> Add bbr team

- config/cf-docs.yml
> add working hours to no interrupt msg
